services:
  - type: cron
    name: export-to-google-sheets
    runtime: python
    schedule: "@hourly"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python export_to_sheets.py"
    envVars:
      - key: DB_HOST
        value: 172.16.88.11
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: production_payda
      - key: DB_USER
        value: tech_read_user
      - key: DB_PASSWORD
        value: AqIXe52814BvKIWIBbpM
      - key: GOOGLE_SHEET_NAME
        value: grafana_export
      - key: CREDENTIALS_FILE
        value: credentials.json
